Repository sethverrill/smart-gardening-be, pull requests merged in 2025-01, with the labels that each got.

#24 Db seeds
  .rspec
  Gemfile
  Gemfile.lock
  app/models/garden.rb
  app/models/garden_plant.rb
  app/models/plant.rb
  db/migrate/20250108230855_create_gardens.rb
  db/migrate/20250108231102_create_plants.rb
  db/migrate/20250108231128_create_garden_plants.rb
  db/schema.rb
  db/seeds.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: BE Ticket

#28 Update Ruby version to work with Heroku
  Gemfile
  Gemfile.lock
Labels: bug

#34 Model specs
  config/credentials.yml.enc
  db/seeds.rb
  spec/models/garden_plant_spec.rb
  spec/models/garden_spec.rb
  spec/models/plant_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: BE Ticket

#47 Save garden
  app/controllers/api/v1/gardens_controller.rb
  config/routes.rb
  spec/requests/api/v1/gardens_controller_spec.rb
  spec/requests/api/v1/gardens_request_spec.rb
Labels: BE Ticket, FE Ticket

#49 OpenAI API functionality
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/recommendation_controller.rb
  app/gateways/openai_gateway.rb
  app/poros/recommendation_params_processor.rb
  app/serializers/recommendation_serializer.rb
  spec/fixtures/openai_gateway_stubbed.json
  spec/fixtures/recommendation_stubbed_response.json
  spec/gateways/openai_gateway_spec.rb
  spec/poros/recommentation_params_processor_spec.rb
  spec/requests/api/v1/recommendation_request_spec.rb
Labels: BE Ticket
